// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// Prisma 6 doesn't use prisma.config.ts
// Configuration is in schema.prisma
